rpcuser=signetuser
rpcpassword=signetpassword
signet=1
[signet]
rpcport=38332
add-node=127.0.0.1:8080
add-node=127.0.0.1:$(gnostr-weeble)
daemon=1
signetchallenge=0014e4949ae1b9c0910e031c865fdcdf07efc2a11016
